import React from "react";

const TermsConditionPage = () => {
  return (
    <>
      <h1>Terms of Service</h1>

      <p>By using this app, you agree to these terms.</p>

      <h2>Usage</h2>
      <ul>
        <li>
          This app is intended for personal or business use to generate design
          assets.
        </li>
        <li>You agree not to use it for illegal or harmful activities.</li>
      </ul>

      <h2>AI-Generated Content</h2>
      <p>
        The results are generated by AI and are intended to be used as
        inspiration or suggestions. We do not guarantee factual accuracy or
        copyright ownership of the generated content.
      </p>

      <h2>Liability</h2>
      <p>
        We are not liable for how users use the generated content. Use it
        responsibly.
      </p>
    </>
  );
};

export default TermsConditionPage;
