const TermsConditionPage = () => {
  return (
    <div className="container">
      <h1>Terms of Service</h1>

      <p>By using this app, you agree to the following terms.</p>

      <h2>Usage</h2>
      <ul>
        <li>
          This app is designed for personal or business use to generate design
          assets like color palettes.
        </li>
        <li>
          You agree not to use the app for any illegal, harmful, or abusive
          purposes.
        </li>
      </ul>

      <h2>AI-Generated Content</h2>
      <p>
        The content generated by this app is powered by AI and should be used as
        creative inspiration or suggestions. We do not guarantee accuracy,
        originality, or ownership of the generated results.
      </p>

      <h2>Liability</h2>
      <p>
        This tool simply generates color palettes. How you choose to use them is
        entirely up to you. We are not responsible for any outcomes—please use
        the tool responsibly.
      </p>
    </div>
  );
};

export default TermsConditionPage;
